# Definition for the min blog engine deployment. This would normally be stored separatedly 
# so the app can be configured independently of the code.
service: simpleblog
vm: 1
api_version: 1
skip_files:
  - ^.*$

# Configuration of the engine.
env_variables:
  SIMPLEBLOG_STORAGE_BUCKET: tryinggce.appspot.com